name: white_label_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  carousel_slider: 4.0.0-nullsafety.0
  cloud_firestore: ^2.2.2
  get: ^4.1.4
  responsive_builder: ^0.4.1
  responsive_framework: ^0.1.2
  responsive_grid: ^2.0.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/contacts/
    - assets/img/products/
